<?php
/**
 * CampaignApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SalesForce\MarketingCloud\Test\Api;

use SalesForce\MarketingCloud\TestHelper\Api\BaseApiTest;

/**
 * CampaignApiTest Class Doc Comment
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignApiTest extends BaseApiTest
{
    /**
     * The client class to use in order to build the client object
     *
     * @var string
     */
    protected $clientClass = \SalesForce\MarketingCloud\Api\CampaignApi::class;

    /**
     * @var string
     */
    protected static $modelNamespace = "\SalesForce\MarketingCloud\Model";

    
    /**
     * Test case for createCampaign
     *
     * createCampaign.
     * @throws \Exception
     */
    public function testCreateCampaign()
    {
        $this->setHttpMethod("POST");

        // Looking for a decorator first
        /** @var \SalesForce\MarketingCloud\TestHelper\Decorator\CampaignApiDecorator $decorator */
        $decorator = $this->getDecorator();
        if (method_exists($decorator, "testCreateCampaign")) {
            return $decorator->testCreateCampaign();
        }
        
        // Setting up the resource creator
        $resourceCreator = $this->getResourceCreator();
        $resourceCreator->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\Campaign"
        );

        // SUT
        $this->createResourceOnEndpoint();
        $this->executeOperation("createCampaign");
    }
    
    /**
     * Test case for deleteCampaignById
     *
     * deleteCampaignById.
     * @throws \Exception
     */
    public function testDeleteCampaignById()
    {
        $this->setHttpMethod("DELETE");

        // Looking for a decorator first
        /** @var \SalesForce\MarketingCloud\TestHelper\Decorator\CampaignApiDecorator $decorator */
        $decorator = $this->getDecorator();
        if (method_exists($decorator, "testDeleteCampaignById")) {
            return $decorator->testDeleteCampaignById();
        }
        
        // Setting up the resource creator
        $resourceCreator = $this->getResourceCreator();
        $resourceCreator->setModelClass(
            __FUNCTION__,
            ""
        );

        // SUT
        $this->createResourceOnEndpoint();
        $this->executeOperation("deleteCampaignById");
    }
    
    /**
     * Test case for getCampaignById
     *
     * getCampaignById.
     * @throws \Exception
     */
    public function testGetCampaignById()
    {
        $this->setHttpMethod("GET");

        // Looking for a decorator first
        /** @var \SalesForce\MarketingCloud\TestHelper\Decorator\CampaignApiDecorator $decorator */
        $decorator = $this->getDecorator();
        if (method_exists($decorator, "testGetCampaignById")) {
            return $decorator->testGetCampaignById();
        }
        
        // Setting up the resource creator
        $resourceCreator = $this->getResourceCreator();
        $resourceCreator->setModelClass(
            __FUNCTION__,
            "\SalesForce\MarketingCloud\Model\Campaign"
        );

        // SUT
        $this->createResourceOnEndpoint();
        $this->executeOperation("getCampaignById");
    }
}
