<?php
/**
 * SendDefinitionResponseItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SalesForce\MarketingCloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SendDefinitionResponseItemTest Class Doc Comment
 *
 * @category    Class
 * @description SendDefinitionResponseItem
 * @package     SalesForce\MarketingCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SendDefinitionResponseItemTest extends TestCase
{
    /**
     * Test "SendDefinitionResponseItem"
     */
    public function testSendDefinitionResponseItem()
    {
    }

    /**
     * Test attribute "messageKey"
     */
    public function testPropertyMessageKey()
    {
    }

    /**
     * Test attribute "errorCode"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }
}
