<?php
/**
 * AssetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SalesForce\MarketingCloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AssetTest Class Doc Comment
 *
 * @category    Class
 * @description Asset
 * @package     SalesForce\MarketingCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AssetTest extends TestCase
{
    /**
     * Test "Asset"
     */
    public function testAsset()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "customerKey"
     */
    public function testPropertyCustomerKey()
    {
    }

    /**
     * Test attribute "contentType"
     */
    public function testPropertyContentType()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "assetType"
     */
    public function testPropertyAssetType()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "locked"
     */
    public function testPropertyLocked()
    {
    }

    /**
     * Test attribute "fileProperties"
     */
    public function testPropertyFileProperties()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "design"
     */
    public function testPropertyDesign()
    {
    }

    /**
     * Test attribute "superContent"
     */
    public function testPropertySuperContent()
    {
    }

    /**
     * Test attribute "customFields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "views"
     */
    public function testPropertyViews()
    {
    }

    /**
     * Test attribute "blocks"
     */
    public function testPropertyBlocks()
    {
    }

    /**
     * Test attribute "minBlocks"
     */
    public function testPropertyMinBlocks()
    {
    }

    /**
     * Test attribute "maxBlocks"
     */
    public function testPropertyMaxBlocks()
    {
    }

    /**
     * Test attribute "channels"
     */
    public function testPropertyChannels()
    {
    }

    /**
     * Test attribute "allowedBlocks"
     */
    public function testPropertyAllowedBlocks()
    {
    }

    /**
     * Test attribute "slots"
     */
    public function testPropertySlots()
    {
    }

    /**
     * Test attribute "businessUnitAvailability"
     */
    public function testPropertyBusinessUnitAvailability()
    {
    }

    /**
     * Test attribute "sharingProperties"
     */
    public function testPropertySharingProperties()
    {
    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {
    }

    /**
     * Test attribute "file"
     */
    public function testPropertyFile()
    {
    }

    /**
     * Test attribute "generateFrom"
     */
    public function testPropertyGenerateFrom()
    {
    }
}
