<?php
/**
 * EmailDefinitionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SalesForce\MarketingCloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EmailDefinitionTest Class Doc Comment
 *
 * @category    Class
 * @description EmailDefinition
 * @package     SalesForce\MarketingCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmailDefinitionTest extends TestCase
{
    /**
     * Test "EmailDefinition"
     */
    public function testEmailDefinition()
    {
    }

    /**
     * Test attribute "requestId"
     */
    public function testPropertyRequestId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "definitionKey"
     */
    public function testPropertyDefinitionKey()
    {
    }

    /**
     * Test attribute "definitionId"
     */
    public function testPropertyDefinitionId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "classification"
     */
    public function testPropertyClassification()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "createdDate"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "modifiedDate"
     */
    public function testPropertyModifiedDate()
    {
    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {
    }

    /**
     * Test attribute "subscriptions"
     */
    public function testPropertySubscriptions()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }
}
