<?php
/**
 * GetDefinitionsNotSentToRecipientsMessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SalesForce\MarketingCloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetDefinitionsNotSentToRecipientsMessageTest Class Doc Comment
 *
 * @category    Class
 * @description GetDefinitionsNotSentToRecipientsMessage
 * @package     SalesForce\MarketingCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetDefinitionsNotSentToRecipientsMessageTest extends TestCase
{
    /**
     * Test "GetDefinitionsNotSentToRecipientsMessage"
     */
    public function testGetDefinitionsNotSentToRecipientsMessage()
    {
    }

    /**
     * Test attribute "statusCode"
     */
    public function testPropertyStatusCode()
    {
    }

    /**
     * Test attribute "statusMessage"
     */
    public function testPropertyStatusMessage()
    {
    }

    /**
     * Test attribute "eventCategoryType"
     */
    public function testPropertyEventCategoryType()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "definitionKey"
     */
    public function testPropertyDefinitionKey()
    {
    }

    /**
     * Test attribute "eventID"
     */
    public function testPropertyEventID()
    {
    }

    /**
     * Test attribute "info"
     */
    public function testPropertyInfo()
    {
    }
}
