<?php
/**
 * GetDefinitionSendStatusForRecipientResponseInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SalesForce\MarketingCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketing Cloud REST API
 *
 * Marketing Cloud's REST API is our newest API. It supports multi-channel use cases, is much more lightweight and easy to use than our SOAP API, and is getting more comprehensive with every release.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: mc_sdk@salesforce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SalesForce\MarketingCloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetDefinitionSendStatusForRecipientResponseInfoTest Class Doc Comment
 *
 * @category    Class
 * @description GetDefinitionSendStatusForRecipientResponseInfo
 * @package     SalesForce\MarketingCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetDefinitionSendStatusForRecipientResponseInfoTest extends TestCase
{
    /**
     * Test "GetDefinitionSendStatusForRecipientResponseInfo"
     */
    public function testGetDefinitionSendStatusForRecipientResponseInfo()
    {
    }

    /**
     * Test attribute "messageKey"
     */
    public function testPropertyMessageKey()
    {
    }

    /**
     * Test attribute "contactKey"
     */
    public function testPropertyContactKey()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "statusCode"
     */
    public function testPropertyStatusCode()
    {
    }

    /**
     * Test attribute "statusMessage"
     */
    public function testPropertyStatusMessage()
    {
    }
}
